module.exports={
    entry:"./index.js",
    output:{
        path:__dirname,
        filename:'bundle.js',
    },
    devtool:'source-map',
    module:{
        loaders:[
            {test:/\.css$/,loader:'style-loader!css-loader'},
            {test:/\.js$/,loader:'babel-loader',exclude:/node_modules/}, 
        ]
    }
}